### ISSUE TITLE
Doesn't work with the latest VirtualBox Version

### ISSUE THREAD

**Issue by luissantos** [fishi0x01/vagrant-boxes#2]
It seems like the flag --clipboard got renamed to --clipboard-mode in 6.1.

More details: https://github.com/hashicorp/vagrant/issues/11288

**Comment by fishi0x01** [comment]
Thank you for letting me know and sorry for my late response. I am looking into this in the coming days :+1:

**Comment by fishi0x01** [comment]
Uploaded a new version that also works with vbox >= 6.1.0

https://app.vagrantup.com/fishi0x01/boxes/win-10-pro-x64/versions/2020.03.09
